# Generated by Django 3.2.7 on 2021-12-06 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('item', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
