# Generated by Django 3.2.7 on 2021-12-16 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('meal_type', models.CharField(choices=[('bf', 'Breakfast'), ('ln', 'Launch'), ('dn', 'Dinner')], max_length=10)),
                ('food_type', models.CharField(max_length=15, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
