# Generated by Django 3.2.7 on 2021-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211217_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='food_type',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
