# Generated by Django 3.2.7 on 2021-12-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_tag_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='meal_type',
        ),
    ]
