# Generated by Django 3.2.7 on 2021-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_tag_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='food_type',
        ),
        migrations.AddField(
            model_name='tag',
            name='meal_type',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('ln', 'Launch'), ('dn', 'Dinner')], max_length=10, null=True),
        ),
    ]
