# Generated by Django 3.2.7 on 2021-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_tag_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
    ]
