# Generated by Django 3.2.7 on 2021-12-17 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_tag_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
