# Generated by Django 3.2.7 on 2021-12-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211217_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='food_type',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner')], max_length=10),
        ),
    ]
