# Generated by Django 3.2.7 on 2021-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
