# Generated by Django 3.2.7 on 2021-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='food_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner')], max_length=10, null=True),
        ),
    ]
