# Generated by Django 3.2.7 on 2021-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20211218_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='food_type',
        ),
        migrations.AlterField(
            model_name='tag',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=10, null=True, unique=True),
        ),
    ]
