# Generated by Django 3.2.7 on 2021-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20211218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=10, null=True, unique=True),
        ),
    ]
