# Generated by Django 3.2.7 on 2021-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_tag_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
    ]
