# Generated by Django 3.2.7 on 2021-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
